# Build and test stage
FROM maven:3.9.1-openjdk-11 AS build
WORKDIR /app
COPY . .
RUN mvn clean test package


# Final packaging stage
FROM maven:3.9.1-openjdk-11
WORKDIR /app
COPY --from=build /app/target/accenture-techhub-0.0.1-SNAPSHOT.war .
EXPOSE 8080
CMD ["java", "-jar", "accenture-techhub-0.0.1-SNAPSHOT.war"]
