# Dockerfile for MySQL

# Use an official MySQL image
FROM mysql:latest

# Environment variables to configure the database
MYSQL_ROOT_PASSWORD=mysecretpassword \
MYSQL_USER=admin \
MYSQL_PASSWORD=1234

# Copy the database initialization script
COPY init.sql /docker-entrypoint-initdb.d/

# Default port for MySQL
EXPOSE 3306