
FROM maven:latest AS build
WORKDIR /app
COPY pom.xml .
COPY src src
RUN mvn clean package


FROM build AS test
RUN mvn test

FROM tomcat:9.0-jre11-slim
COPY target/accenture-techhub-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
EXPOSE 5501
CMD ["catalina.sh", "run"]